DROP TABLE MEDICAL_PROBLEMS CASCADE CONSTRAINTS;

DROP SEQUENCE MEDICAL_PROBLEMS_SEQ;

DROP TRIGGER MEDICAL_PROBLEMS_TRIGGER;

CREATE TABLE MEDICAL_PROBLEMS (
    ID INT PRIMARY KEY,
    PROBLEM_NAME VARCHAR(100),
    COST NUMBER
);

ALTER TABLE MEDICAL_PROBLEMS
    ADD CONSTRAINT UNIQUE_PROBLEM_NAME UNIQUE (
        PROBLEM_NAME
    );

CREATE SEQUENCE MEDICAL_PROBLEMS_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE OR REPLACE TRIGGER MEDICAL_PROBLEMS_TRIGGER BEFORE
    INSERT ON MEDICAL_PROBLEMS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := MEDICAL_PROBLEMS_SEQ.NEXTVAL;
    END IF;
END;